name: Publish Python 🎯 to PyPI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tool
        run: python -m pip install --upgrade pip build

      - name: Build source & wheel
        run: python -m build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages
          path: dist/
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/famCircle/
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Download dist-packages
        uses: actions/download-artifact@v4
        with:
          name: dist-packages
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
